[build]
  command = "sed -i \"s|{SERVER_HOST}|${DEPLOY_PRIME_URL}|g\" netlify.toml && npm install && npm run build"
  functions = "functions/"
  publish = "dist/"

[[redirects]]
  from = "/api/*"
  to = "{SERVER_HOST}/.netlify/functions/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    Access-Control-Allow-Origin = "*"
    Access-Control-Request-Method = "GET, POST, OPTIONS"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Request-Method = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, X-Auth-Token, Access-Control-Allow-Origin"
